services:

  db:
    image: mysql:9.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: siae-dev
      MYSQL_DATABASE: siae 
      MYSQL_USER: siae 
      MYSQL_PASSWORD: siae 
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
