erDiagram
    Pessoas {
        string CPF PK
        string NomeCompleto
        %% Info residencial %%
        int CepID FK
        %% Usuario associado a pessoa %%
        int UsuarioID FK
        %% Campos sistemicos %%
        int UsuarioModificacaoID FK
        boolean FlagAtivo
        datetime DataInsercao
        datetime DataAtualizacao
    }
    Usuarios {
        int UsuarioID PK
        int TipoUsuarioID FK
        string Login
        string Senha
        %% Campos sistemicos %%
        int UsuarioModificacaoID FK
        boolean FlagAtivo
        datetime DataInsercao
        datetime DataAtualizacao
    }
    %% Dominio com os perfis de usuario possiveis %%
    TiposUsuarios {
        int TipoUsuarioID PK
        string Tipo
        string Descricao
        %% Campos sistemicos %%
        int UsuarioModificacaoID FK
        boolean FlagAtivo
        datetime DataInsercao
        datetime DataAtualizacao
    }
    Clientes {
        int ClienteID PK
        string CPF FK
        %% Campos sistemicos %%
        int UsuarioModificacaoID FK
        boolean FlagAtivo
        datetime DataInsercao
        datetime DataAtualizacao
    }
    %% Sera buscado e populado CEP via API %%
    Enderecos {
        int CepID PK
        string Logradouro
        string Bairro
        string Cidade
        string UF
        %% Campos sistemicos %%
        int UsuarioModificacaoID FK
        boolean FlagAtivo
        datetime DataInsercao
        datetime DataAtualizacao
    }
    EnderecosPessoas {
        int EnderecoPessoaID PK
        int CPF FK
        int CepID FK
        string Numero
        string Complemento
        %% Campos sistemicos %%
        int UsuarioModificacaoID FK
        boolean FlagAtivo
        datetime DataInsercao
        datetime DataAtualizacao
    }
    ContatosPessoas {
        int ContatoPessoaID PK
        int CPF FK
        int TipoContatoID FK
        string ValorContato
        boolean FlagPreferencial
        %% Campos sistemicos %%
        int UsuarioModificacaoID FK
        boolean FlagAtivo
        datetime DataInsercao
        datetime DataAtualizacao
    }
    TiposContatos {
        int TipoContatoID PK
        string TipoContato
        string Descricao
        %% Campos sistemicos %%
        int UsuarioModificacaoID FK
        boolean FlagAtivo
        datetime DataInsercao
        datetime DataAtualizacao
    }
    %% Poderia ser populado inicialmente em batch %%
    Veiculos {
        int VeiculoID PK
        string Modelo
        string Marca
        string AnoFabricacao
        string AnoModelo
        string Motorizacao
        int TipoCombustivelID FK
        %% Campos sistemicos %%
        boolean FlagAtivo
        datetime DataInsercao
        datetime DataAtualizacao
    }
    TiposCombustiveis {
        int TipoCombustivelID PK
        string Tipo
        string Descricao
        %% Campos sistemicos %%
        int UsuarioModificacaoID FK
        boolean FlagAtivo
        datetime DataInsercao
        datetime DataAtualizacao
    }
    VeiculosClientes {
        int VeiculoClienteID PK
        int VeiculoID FK
        int ClienteID FK
        string Placa
        string Cor
        string DescricaoVeiculo
        %% Campos sistemicos %%
        int UsuarioModificacaoID FK
        boolean FlagAtivo
        datetime DataAtualizacao
    }
    TiposStatusOrdemDeServico {
        int TipoStatusID PK
        string DescricaoStatus
        %% Campos sistemicos %%
        int UsuarioModificacaoID FK
        boolean FlagAtivo
        datetime DataInsercao
        datetime DataAtualizacao
    }
    OrdensDeServicos {
        int OrdemDeServicoID PK
        int ClienteID FK
        int VeiculoClienteID FK
        int Quilometragem
        decimal ValorTotal
        decimal ValorTotalPecas
        decimal ValorTotalServicos
        datetime DataSolicitacao
        datetime DataInicio
        datetime DataFim
        int TipoStatusID FK
        %% Campos sistemicos %%
        int UsuarioModificacaoID FK
        boolean FlagAtivo
        datetime DataInsercao
        datetime DataAtualizacao
    }
    OrdensDeServicosPecasInsumos {
        int OrdemDeServicoID PK
        int PecaInsumoID PK
        int Quantidade
        decimal ValorTotal
        %% Campos sistemicos %%
        int UsuarioModificacaoID FK
        boolean FlagAtivo
        datetime DataInsercao
        datetime DataAtualizacao
    }
    OrdensDeServicosServicos {
        int OrdemDeServicoServicoID PK
        int OrdemDeServicoID FK
        int ServicoID FK
        int MecanicoID FK
        %% Campos sistemicos %%
        int UsuarioModificacaoID FK
        boolean FlagAtivo
        datetime DataInsercao
        datetime DataAtualizacao
    }
    %% Poderia ser populado inicialmente em batch %%
    Servicos{
        int ServicoID PK
        string Descricao
        decimal ValorServico
        int UsuarioModificacaoID FK
        %% Campos sistemicos %%
        boolean FlagAtivo
        datetime DataInsercao
        datetime DataAtualizacao
    }
    %% Poderia ser populado inicialmente em batch %%
    PecasInsumos {
        int PecaInsumoID PK
        string Descricao
        string Marca
        string Fabricante
        decimal ValorUnitario
        %% Campos sistemicos %%
        int QuantidadeDisponivel
        int UsuarioModificacaoID FK
        boolean FlagAtivo
        datetime DataInsercao
        datetime DataAtualizacao
    }
    OperacoesEstoques {
        int OperacaoEstoqueID PK
        int OrdemDeServicoPecasInsumosID FK
        int PecaInsumoID FK
        int TipoOperacaoEstoqueID FK
        int Quantidade
        datetime DataOperacao
    }
    TiposOperacaoEstoque {
        int TipoOperacaoEstoqueID PK
        string DescricaoOperacao
        %% Campos sistemicos %%
        int UsuarioModificacaoID FK
        boolean FlagAtivo
        datetime DataInsercao
        datetime DataAtualizacao
    }

    Enderecos ||--o{ EnderecosPessoas : possui
    EnderecosPessoas }o--|| Pessoas : possui

    Pessoas ||--|| Usuarios : "possui"
    Pessoas ||--o| Clientes : "pode ser"
    Pessoas ||--o{ ContatosPessoas : possui

    ContatosPessoas }o--|| TiposContatos : possui

    Usuarios }o--|| TiposUsuarios : possui

    Clientes ||--|{ VeiculosClientes: possui

    Veiculos }o--|| TiposCombustiveis: possui

    VeiculosClientes }|--|| Veiculos: possui

    OrdensDeServicos }|--|| TiposStatusOrdemDeServico : possui

    OrdensDeServicos }o--|| Clientes: contem
    OrdensDeServicos }o--|| VeiculosClientes: contem

    OrdensDeServicos ||--|{ OrdensDeServicosServicos: contem
    OrdensDeServicos ||--o{ OrdensDeServicosPecasInsumos: contem

    OrdensDeServicosServicos }|--|| Servicos: contem
    OrdensDeServicosPecasInsumos }o--|| PecasInsumos: contem

    OperacoesEstoques }o--|| PecasInsumos: contem
    OperacoesEstoques }o--|| TiposOperacaoEstoque: contem
    OperacoesEstoques ||--|| OrdensDeServicosPecasInsumos: contem