[project]
name = "py-fastapi-mecanica-siaes"
version = "0.1.0"
description = "Basic CRUD system for customer"
readme = "README.md"
requires-python = "==3.14.6"
dependencies = [
    "fastapi[standard]",
    "SQLAlchemy==2.0.51",
    "pyjwt==2.13.0",
    "pymysql==1.2.0",
]

[tool.fastapi]
entrypoint = "main:app"

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests/unit"]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]
