[project]
name = "py-fastapi-mecanica-siaes"
version = "0.1.0"
description = "Basic CRUD system for customer"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]",
    "psycopg[binary]",
    "pytest>=9.1.1",
    "behave",
    "SQLAlchemy",
]

[tool.fastapi]
entrypoint = "main:app"

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests/unit"]
