erDiagram
    Pessoas {
        string PersonID PK
        string NomeCompleto
        boolean FlagCliente
        %% Usuario associado a pessoa (1:1, unique) %%
        int UsuarioID FK
        %% Campos sistemicos %%
        int UsuarioModificacaoID
        boolean FlagAtivo
        datetime DataInsercao
        datetime DataAtualizacao
    }
    Usuarios {
        int UsuarioID PK
        string TipoUsuario
        string Login
        string Senha
        %% Campos sistemicos %%
        int UsuarioModificacaoID
        boolean FlagAtivo
        datetime DataInsercao
        datetime DataAtualizacao
    }
    %% Sera buscado e populado CEP via API %%
    Enderecos {
        int CepID PK
        string Logradouro
        string Bairro
        string Cidade
        string UF
        %% Campos sistemicos %%
        int UsuarioModificacaoID
        boolean FlagAtivo
        datetime DataInsercao
        datetime DataAtualizacao
    }
    EnderecosPessoas {
        int EnderecoPessoaID PK
        string PersonID FK
        int CepID FK
        string Numero
        string Complemento
        %% Campos sistemicos %%
        int UsuarioModificacaoID
        boolean FlagAtivo
        datetime DataInsercao
        datetime DataAtualizacao
    }
    ContatosPessoas {
        int ContatoPessoaID PK
        string PersonID FK
        string TipoContato
        string ValorContato
        boolean FlagPreferencial
        %% Campos sistemicos %%
        int UsuarioModificacaoID
        boolean FlagAtivo
        datetime DataInsercao
        datetime DataAtualizacao
    }
    VeiculosClientes {
        int VeiculoClienteID PK
        string PersonID FK
        string Modelo
        string Marca
        string AnoFabricacao
        string AnoModelo
        string Motorizacao
        string TipoCombustivel
        string Placa
        string Cor
        string DescricaoVeiculo
        %% Campos sistemicos %%
        int UsuarioModificacaoID
        boolean FlagAtivo
        datetime DataInsercao
        datetime DataAtualizacao
    }
    OrdensDeServicos {
        int OrdemDeServicoID PK
        string PersonID FK
        int VeiculoClienteID FK
        int Quilometragem
        string DescricaoProblema
        string Diagnostico
        int MecanicoUsuarioID FK
        decimal ValorTotal
        decimal ValorTotalPecas
        decimal ValorTotalServicos
        int EstimativaTempoDias
        string ObservacaoOrcamento
        datetime DataSolicitacao
        datetime DataInicio
        datetime DataFim
        string Status
        %% Campos sistemicos %%
        int UsuarioModificacaoID
        boolean FlagAtivo
        datetime DataInsercao
        datetime DataAtualizacao
    }
    OrdensDeServicosPecasInsumos {
        int OrdemDeServicoPecaInsumoID PK
        int OrdemDeServicoID FK
        int PecaInsumoID FK
        int Quantidade
        decimal ValorTotal
        %% Campos sistemicos %%
        int UsuarioModificacaoID
        datetime DataInsercao
    }
    OrdensDeServicosServicos {
        int OrdemDeServicoServicoID PK
        int OrdemDeServicoID FK
        int ServicoID FK
        int MecanicoUsuarioID FK
        %% Campos sistemicos %%
        int UsuarioModificacaoID
        datetime DataInsercao
    }
    %% Poderia ser populado inicialmente em batch %%
    Servicos{
        int ServicoID PK
        string Descricao
        decimal ValorServico
        int TempoMedioMinutos
        int UsuarioModificacaoID
        %% Campos sistemicos %%
        boolean FlagAtivo
        datetime DataInsercao
        datetime DataAtualizacao
    }
    %% Poderia ser populado inicialmente em batch %%
    PecasInsumos {
        int PecaInsumoID PK
        string Descricao
        string Marca
        string Fabricante
        decimal ValorUnitario
        %% Campos sistemicos %%
        int QuantidadeDisponivel
        int UsuarioModificacaoID
        boolean FlagAtivo
        datetime DataInsercao
        datetime DataAtualizacao
    }
    OperacoesEstoques {
        int OperacaoEstoqueID PK
        int OrdemDeServicoPecasInsumosID FK
        int PecaInsumoID FK
        string TipoOperacaoEstoque
        int Quantidade
        int UsuarioModificacaoID
        datetime DataOperacao
    }

    Enderecos ||--o{ EnderecosPessoas : possui
    EnderecosPessoas }o--|| Pessoas : possui

    Pessoas ||--|| Usuarios : "possui"
    Pessoas ||--o{ ContatosPessoas : possui
    Pessoas ||--o{ VeiculosClientes: possui

    OrdensDeServicos }o--|| Pessoas: contem
    OrdensDeServicos }o--|| VeiculosClientes: contem

    OrdensDeServicos ||--|{ OrdensDeServicosServicos: contem
    OrdensDeServicos ||--o{ OrdensDeServicosPecasInsumos: contem

    OrdensDeServicosServicos }|--|| Servicos: contem
    OrdensDeServicosPecasInsumos }o--|| PecasInsumos: contem

    OperacoesEstoques }o--|| PecasInsumos: contem
    OperacoesEstoques ||--|| OrdensDeServicosPecasInsumos: contem